### PR TITLE
Disable debugging in release builds, part 2

### PR DESCRIPTION
**Pull request by steven-bellock**
Signed-off-by: Steven Bellock <sbellock@nvidia.com>

### CODE REVIEW

**Comment by steven-bellock** [comment]
The two logs : 
https://github.com/DMTF/libspdm/runs/8059869756?check_suite_focus=true#step:15:382
https://github.com/DMTF/libspdm/runs/8059869756?check_suite_focus=true#step:15:439

Interestingly when I run this locally I also see a stack-buffer-underflow in `test_spdm_requester_finish`.

**Comment by liuw1** [comment]
@Xiaohanjlll Could you please help to take a look at the overflow issues that steven mentioned.

**Comment by steven-bellock** [comment]
Stack trace from `test_spdm_requester_finish` when I run locally.
```
Running: ./seeds/test_spdm_requester_finish/finish11.raw
=================================================================
==53691==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffc131a9480 at pc 0x000000624eb8 bp 0x7ffc131a9440 sp 0x7ffc131a9438
READ of size 1 at 0x7ffc131a9480 thread T0
    #0 0x624eb7 in libspdm_const_compare_mem /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/os_stub/memlib/compare_mem.c:45:37
    #1 0x56fd09 in libspdm_verify_finish_rsp_hmac /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/library/spdm_common_lib/libspdm_com_crypto_service_session.c:1515:9
    #2 0x5625f6 in libspdm_try_send_receive_finish /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/library/spdm_requester_lib/libspdm_req_finish.c:263:18
    #3 0x5617dd in libspdm_send_receive_finish /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/library/spdm_requester_lib/libspdm_req_finish.c:322:18
    #4 0x55f076 in libspdm_test_send_receive_finish_case1 /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c:145:5
    #5 0x5604f4 in libspdm_run_test_harness /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c:365:5
    #6 0x561334 in LLVMFuzzerTestOneInput /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c:124:5
    #7 0x469701 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/scratch.sbellock_sw/temp/steven-bellock/libspdm/build/bin/test_spdm_requester_finish+0x469701)
    #8 0x454e72 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/scratch.sbellock_sw/temp/steven-bellock/libspdm/build/bin/test_spdm_requester_finish+0x454e72)
    #9 0x45a926 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/scratch.sbellock_sw/temp/steven-bellock/libspdm/build/bin/test_spdm_requester_finish+0x45a926)
    #10 0x4835e2 in main (/home/scratch.sbellock_sw/temp/steven-bellock/libspdm/build/bin/test_spdm_requester_finish+0x4835e2)
    #11 0x7f040d7790b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #12 0x42f53d in _start (/home/scratch.sbellock_sw/temp/steven-bellock/libspdm/build/bin/test_spdm_requester_finish+0x42f53d)

Address 0x7ffc131a9480 is located in stack of thread T0 at offset 0 in frame
    #0 0x56f91f in libspdm_verify_finish_rsp_hmac /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/library/spdm_common_lib/libspdm_com_crypto_service_session.c:1447

  This frame has 8 object(s):
    [32, 96) 'calc_hmac_data' (line 1449)
    [128, 136) 'cert_chain_buffer' (line 1452)
    [160, 168) 'cert_chain_buffer_size' (line 1453)
    [192, 200) 'mut_cert_chain_buffer' (line 1454)
    [224, 232) 'mut_cert_chain_buffer_size' (line 1455)
    [256, 4864) 'th_curr_data' (line 1456)
    [5120, 5128) 'th_curr_data_size' (line 1457)
    [5152, 5216) 'hash_data' (line 1458)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/scratch.sbellock_sw/temp/steven-bellock/libspdm/os_stub/memlib/compare_mem.c:45:37 in libspdm_const_compare_mem
```

**Comment by Wenxing-hou** [comment]
The [get_measurement fuzzing error](https://github.com/DMTF/libspdm/runs/8059869756?check_suite_focus=true#step:15:439) may be a regression for the patch [Fix fuzzy test cases](https://github.com/DMTF/libspdm/commit/22baa6bf721691fa502b0a2c4790bc6d6625d5fc). The get_measurement fuzzing error disappeared before this patch.  
The function `libspdm_test_requester_get_measurement_case1` is fuzzing error location.

**Comment by jyao1** [comment]
try again after https://github.com/DMTF/libspdm/pull/1210

**Comment by Wenxing-hou** [comment]
The fuzzing error is fixed.

**Comment by jyao1** [comment]
@steven-bellock , please resolve CodeQL issue.
After that we can merge. The fuzzing issue is resolved in latest version.

**Pull request merged**
