### PR TITLE
Check transport length in libspdm_mctp_encode_message()

### PR DESCRIPTION
**Pull request by xiangfeima**
Fix: #796

Signed-off-by: Xiangfei Ma <xiangfei.ma@samsung.com>

### CODE REVIEW

**Comment by steven-bellock** [comment]
@jyao1 I don't have an opinion on this one. So merge as you see fit.

**Comment by jyao1** [comment]
@xiangfeima, May I know what test you have done?  Do you run spdm-emu?

**Comment by xiangfeima** [comment]
Yes, I confirmed that spdm-emu works well with this patch.

**Comment by jyao1** [comment]
@xiangfeima , would you please take a look at https://github.com/DMTF/spdm-emu/pull/225 ?

Any hint on the failure?

**Pull request merged**
