### PR TITLE
Improve the OID check logic in cert extension

### PR DESCRIPTION
**Pull request by Wenxing-hou**
Fix: #2491 
The patch has passed the existing `test_spdm_crypt` unit_test.

### CODE REVIEW

**Comment by jyao1** [comment]
question: What is wrong with original cert?

**Comment by Wenxing-hou** [comment]
> question: What is wrong with original cert?

The original long_chians cert was generated a long time ago, which have the wrong `id-DMTF-hardware-identity`.
The related issue is https://github.com/DMTF/libspdm/issues/2325

**Comment by jyao1** [comment]
How you regenerate the new long_chians cert? I think we need script. Not only update binary.

**Comment by Wenxing-hou** [comment]
> How you regenerate the new long_chians cert? I think we need script. Not only update binary.
> 
> Also, I think regenerating cert should be separated to another PR.

Thanks. I have spilt this PR and submitted the new PR: https://github.com/DMTF/libspdm/pull/2504

**Review by steven-bellock — APPROVED** [review]

**Pull request merged**
