### PR TITLE
Reset Message buffer for interruption

### LINKED ISSUE #27: Need reset MessageM for any interruption
From https://github.com/jyao1/openspdm/issues/172

SPDM spec: Any communication between Requester and Responder other than a GET_MEASUREMENTS request or response resets L1/L2 computation to null.

Also reset MessageB/C for any interrupt:

If the Requester issued GET_MEASUREMENTS or KEY_EXCHANGE or FINISH or PSK_EXCHANGE or PSK_FINISH or KEY_UPDATE or HEARTBEAT or GET_ENCAPSULATED_REQUEST or DELIVER_ENCAPSULATED_RESPONSE or END_SESSSION request(s) and skipped CHALLENGE completion, M1 and M2 are reset to null .

Same criteria for MessageMutB/MutC

### PR DESCRIPTION
**Pull request by liyi77**
Fix #27
Signed-off-by: yi1.li <yi1.li@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
Please add corresponding unit test.

**Comment by liyi77** [comment]
> Please add corresponding unit test.

added unit test case

**Comment by jyao1** [comment]
reviewed-by: Jiewen Yao <jiewen.yao@intel.com>

**Comment by steven-bellock** [comment]
Looks good to me.

**Pull request merged**
