### PR TITLE
fix test case measurements

### PR DESCRIPTION
**Pull request by Xiaohanjlll**
Fix: #2784

### CODE REVIEW

**Comment by Zhiqiang520** [comment]
@steven-bellock @jyao1  please help review and merge this PR, thanks.

**Comment by steven-bellock** [comment]
@Zhiqiang520 I'll rely on your judgement to merge.

**Review by Zhiqiang520 — APPROVED** [review]

**Comment by Zhiqiang520** [comment]
it looks good to me.

**Comment by Zhiqiang520** [comment]
@steven-bellock It looks good to me, please help merge this PR, thanks.

**Pull request merged**
