### PR TITLE
ResponderVerifyData / RequesterVerifyData should use hash of transcript

### PR DESCRIPTION
**Pull request by jyao1**
Fix https://github.com/DMTF/libspdm/issues/1136.

Signed-off-by: Jiewen Yao <jiewen.yao@intel.com>

### CODE REVIEW

**Comment by Wenxing-hou** [comment]
I think `temp_message_k` can be deleted. 
Because `temp_message_k` is used to store transcript for HMAC input before. Now the HMAC input is `digest_context_th`.

**Comment by Wenxing-hou** [comment]
The follow code in `libspdm_calculate_th_hmac_for_exchange_rsp`  may be not needed: 
```
    if (session_info->session_transcript.digest_context_th == NULL) {
        /* trigger message_k to initialize context after finished_key is ready.*/
        status = libspdm_append_message_k (context, spdm_session_info, is_requester, NULL, 0);
        if (LIBSPDM_STATUS_IS_ERROR(status)) {
            return false;
        }
        LIBSPDM_ASSERT(session_info->session_transcript.digest_context_th != NULL);
    }
```
I have passed the unit_test without above code.

Because`libspdm_generate_key_exchange_rsp_hmac`/`libspdm_verify_key_exchange_rsp_hmac`/`libspdm_generate_psk_exchange_rsp_hmac`/`libspdm_verify_psk_exchange_rsp_hmac` will call  `libspdm_calculate_th_hmac_for_exchange_rsp` .

And `libspdm_append_message_k` is called before above four funciton to ensure `digest_context_th` isn't null.

**Comment by jyao1** [comment]
> I think temp_message_k can be deleted.

Good catch. Agree. Fixed.

**Comment by jyao1** [comment]
> The follow code in libspdm_calculate_th_hmac_for_exchange_rsp may be not needed:

Good catch. Agree. Fixed.

**Comment by steven-bellock** [comment]
This pull request is too large for me to comprehend, so feel free to merge it when you see fit. I can present ideas on how to prevent an issue like this from happening again in our next meeting.

**Pull request merged**
