### PR TITLE
Add transcript hash feature

### PR DESCRIPTION
**Pull request by liyi77**
Just send for main structure review.
Just test at emu tool currently because of most related unittest case will be effected by #52.
I will sync unittest and re-send request after #52 be fixed if main structure of this is fine.

### CODE REVIEW

**Comment by liyi77** [comment]
#22

**Comment by liyi77** [comment]
Dump tool cannot decode securedSPDM if message_f and message_k use transcript hash:
...
88 (1628146535) PCI_DOE(1, 2) RSP->REQ SecuredSPDM(0xffffffff) SPDM(11, 0x67) SPDM_PSK_FINISH_RSP () 
89 (1628146535) PCI_DOE(1, 2) (?)->(?) SecuredSPDM(0xffffffff) <Unknown> 
90 (1628146535) PCI_DOE(1, 2) (?)->(?) SecuredSPDM(0xffffffff) <Unknown> 
91 (1628146535) PCI_DOE(1, 2) (?)->(?) SecuredSPDM(0xffffffff) <Unknown> 
...

 I don’t have any inspiration for this question at the moment.

**Comment by jyao1** [comment]
Can we move append_hash_managed_buffer() inside of append_managed_buffer() ?

=================
	return append_managed_buffer(&spdm_context->transcript.message_mut_c,
				     message, message_size);
	#ifdef USE_TRANSCRIPT_HASH
		return append_hash_managed_buffer(spdm_context,
							&spdm_context->transcript.message_mut_c,
							message, message_size);
	#else
		return append_managed_buffer(&spdm_context->transcript.message_mut_c,
				     	message, message_size);
	#endif
=================

**Comment by liyi77** [comment]
> Can we move append_hash_managed_buffer() inside of append_managed_buffer() ?

Another buffer that dont store hash will use append_managed_buffer(), such like messageA, certchain verify, hmac ...
I think that can be distinguished by buffer size(if the size of these two kinds buffer are always different in future),
or use a flag in buffer type.

This makes me think about that should managed buffers used in calculation of certchain verify, hmac... store hash also?
If sure, only the case of messageA needs to be distinguished.

**Comment by liyi77** [comment]
Optimized issue-solving method

**Pull request closed without merging**
