### PR TITLE
Clear up for GET_VERSION/VERSION

### LINKED ISSUE #28: Need more clear up for GET_VERSION/VERSION
From https://github.com/jyao1/openspdm/issues/170

For example: all session states, negotiated algo, etc,

### PR DESCRIPTION
**Pull request by liyi77**
Fix #28
Signed-off-by: yi1 li <yi1.li@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
why not call spdm_init_context()?

**Comment by liyi77** [comment]
> spdm_init_context

I don’t want to clear information that is irrelevant to last connection, such like transport layer func, local version, local capability, etc. 
Especially local cert chain provision, I think that it is hard to retrieve if be cleaned up in get_version phase.

**Comment by jyao1** [comment]
I see. Agree. Then how about we create another function - spdm_reset_context()  and move all code there ?

I really dont want to add so many code in two places.

**Comment by liyi77** [comment]
> I see. Agree. Then how about we create another function - spdm_reset_context() and move all code there ?
> 
> I really dont want to add so many code in two places.

Reasonable, agree

**Comment by jyao1** [comment]
reviewed-by: Jiewen Yao <jiewen.yao@intel.com>

**Comment by steven-bellock** [comment]
Looks good to me.

**Pull request merged**
