### PR TITLE
Openssl 3 work: Replace EC_KEY* with EVP_PKEY*

### PR DESCRIPTION
**Pull request by liyi77**
REF: https://github.com/DMTF/libspdm/issues/1094
Patch1:
Patch2:
  Add 3.0.2 openssl as submodule
Patch3:
  Replace EC_KEY* with EVP_PKEY*

### CODE REVIEW

**Comment by jyao1** [comment]
Would you please clarify what test you have done?

**Comment by liyi77** [comment]
> Would you please clarify what test you have done?

This patch passed all unit_test case.
Due to code base is so far from main branch, emu test is not done.

**Review by steven-bellock — APPROVED** [review]

**Comment by dlansky1** [comment]
Hi,

The subject code change doesn't seem to be included in latest main branch.
Specifically this patch: https://github.com/DMTF/libspdm/pull/1111/commits/b78de2e0f7398e0e77f8069273f226e09b2911f3

Am I missing something? Any plans to merge this to main?

Thanks,

**Comment by steven-bellock** [comment]
The `openssl_3.0.2_eval` feature branch was an early attempt at upgrading to OpenSSL. The actual upgrade happened later and it looks like these changes did not make it to the `main` branch. @dlansky1 please file a new issue and feel free to reference #1094.

**Pull request merged**
