### PR TITLE
Add unit test for MaxSPDMmsgSize less than DataTransferSize.

### PR DESCRIPTION
**Pull request by Zhiqiang520**
Signed-off-by: Zhao, Zhiqiang <zhiqiang.zhao@intel.com>

### CODE REVIEW

**Comment by steven-bellock** [comment]
That's covered by line coverage but not by conditional coverage : https://steven-bellock.github.io/libspdm/coverage_log/library/spdm_requester_lib/libspdm_req_get_capabilities.c.gcov.html#268 I'll edit the gcov script to include more detail in the coverage report.

**Comment by steven-bellock** [comment]
@Zhiqiang520 Can you also add a test for the Responder, if it's not there already?

**Comment by steven-bellock** [comment]
> That's covered by line coverage but not by conditional coverage : https://steven-bellock.github.io/libspdm/coverage_log/library/spdm_requester_lib/libspdm_req_get_capabilities.c.gcov.html#268 I'll edit the gcov script to include more detail in the coverage report.

I enabled conditional / branch coverage. So an issue like this will show up better in the coverage report.

**Comment by Zhiqiang520** [comment]
> @Zhiqiang520 Can you also add a test for the Responder, if it's not there already?

Yes, I have added a test for the Responder.

**Comment by steven-bellock** [comment]
> > @Zhiqiang520 Can you also add a test for the Responder, if it's not there already?
> 
> Yes, I have added a test for the Responder.

Thanks!

**Review by steven-bellock — APPROVED** [review]

**Pull request merged**
