### PR TITLE
Fix incorrect enumeration values in test_spdm_responder_capabilities  test cases

### PR DESCRIPTION
**Pull request by Xiaohanjlll**
Fix : #1182 
Signed-off-by: Xiaohanjlll <hanx.xiao@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
Please describe which issue this PR fixed.

**Review by steven-bellock — APPROVED** [review]

**Comment by Xiaohanjlll** [comment]
> Please describe which issue this PR fixed.

There should be a mistake here.
LIBSPDM_CONNECTION_STATE_AFTER_VERSION  is not in enum

**Comment by jyao1** [comment]
@Xiaohanjlll , I am asking the issue number...

**Comment by Xiaohanjlll** [comment]
> Signed-off-by: Xiaohanjlll [hanx.xiao@intel.com](mailto:hanx.xiao@intel.com)



> @Xiaohanjlll , I am asking the issue number...

I'm sorry

**Pull request merged**
