### PR TITLE
Remove / rename unwanted #includes of stdio.h

### PR DESCRIPTION
**Pull request by steven-bellock**
Fixes https://github.com/DMTF/libspdm/issues/98
Signed-off by sbellock@nvidia.com

### CODE REVIEW

**Comment by jyao1** [comment]
@steven-bellock: CI fails

**Comment by steven-bellock** [comment]
What failure are you seeing? It passes on my fork https://github.com/steven-bellock/libspdm/actions/runs/1533796771

**Comment by jyao1** [comment]
The format error - signed-off missing.

**Comment by steven-bellock** [comment]
Ok let me close this and try again.

**Pull request closed without merging**
