### PR TITLE
Enable CodeQL scan in CI

### PR DESCRIPTION
**Pull request by liuw1**
Fix: #1122 
Signed-off-by: Wei Liu <wei3.liu@intel.com>

### CODE REVIEW

**Comment by liuw1** [comment]
@jyao1 Please help to open CodeQL in actions.

**Comment by steven-bellock** [comment]
Do you know how long it takes to run this? If it takes a long time, to start this may be something we run manually, or every week or so.

**Comment by liuw1** [comment]
> Do you know how long it takes to run this? If it takes a long time, to start this may be something we run manually, or every week or so.

@steven-bellock About 28 minutes. What's your proposal?

**Comment by jyao1** [comment]
Maybe schedule and run once per week? E.g. Saturday night.

**Comment by jyao1** [comment]
Please consider also add a CodeQL section in https://github.com/DMTF/libspdm/blob/main/doc/test.md.
And tell people how to view result.

**Comment by steven-bellock** [comment]
So when you say it's 28 minutes it looks like it's also scanning OpenSSL, MbedTLS, and Cmocka, which we shouldn't be doing. It's the responsibility of those projects to scan for issues. We should just be scanning `libspdm/include`, `libspdm/library` , and files in `libspdm/os_stub` that we've created. Maybe `libspdm/unit_test` too if it helps find bugs.

**Comment by liuw1** [comment]
> So when you say it's 28 minutes it looks like it's also scanning OpenSSL, MbedTLS, and Cmocka, which we shouldn't be doing. It's the responsibility of those projects to scan for issues. We should just be scanning `libspdm/include`, `libspdm/library` , and files in `libspdm/os_stub` that we've created. Maybe `libspdm/unit_test` too if it helps find bugs.

Agree with you, I will update it later.

**Comment by liuw1** [comment]
Currently, CodeQL need 5 minutes to run one round.

**Comment by liuw1** [comment]
Need to resolve the alerts in report link: https://github.com/liuw1/libspdm/pull/2/checks?check_run_id=7848870526

**Pull request closed without merging**
