### PR TITLE
add check for GET_VERSION in session.

### PR DESCRIPTION
**Pull request by jyao1**
Fix https://github.com/DMTF/libspdm/issues/1987

### CODE REVIEW

**Comment by steven-bellock** [comment]
This also applies to `(V)CA`.

**Comment by jyao1** [comment]
I think CA cannot success because of the connection_state check.

**Comment by jyao1** [comment]
```

**Comment by steven-bellock** [comment]
> I think CA cannot success because of the connection_state check.

Ok.

**Review by steven-bellock — APPROVED** [review]

**Pull request merged**
