### PR TITLE
Make need_reset for get_csr and set_cert clear

### PR DESCRIPTION
**Pull request by Wenxing-hou**
Fix: #2061

The current code meet the follow table.
image

### CODE REVIEW

**Comment by jyao1** [comment]
I dont understand the patch. How you resolve #2061 ?

**Comment by jyao1** [comment]
please add unit test to cover those 4 scenario.

**Comment by Wenxing-hou** [comment]
> please add unit test to cover those 4 scenario.

Thanks.
The `libspdm_test_responder_csr_case1` coves the **scenario 4**:  The device can gen CSR without reset.

The `libspdm_test_responder_csr_case6`  covers the **scenario 2 and 3**. In the case6, the device need reset to complete the CSR. The first get_csr request cover the scenario 3.  The second request without device reset cover the scenario 2.


The `libspdm_test_responder_csr_case6`  covers the **scenario 1 and** 3. In the case12, the device need reset to complete the CSR. The first get_csr request cover the scenario 3.  The second request after device reset cover the scenario 2.

**Comment by jyao1** [comment]
Where is test for set_cert ?

**Comment by Wenxing-hou** [comment]
> Where is test for set_cert ?

For normal set_cert request, the unit_test is follow:
https://github.com/DMTF/libspdm/blob/ccfa0f0b959c14c1f8f27051913887a0cb487baf/unit_test/test_spdm_responder/set_certificate_rsp.c#L14-L19

For second set_cert request, the unit_test is in the PR: https://github.com/DMTF/libspdm/pull/2144

**Pull request merged**
