### PR TITLE
Make slot_1 certchain has the same public key with slot_0 

### PR DESCRIPTION
**Pull request by Wenxing-hou**
Fix: #2073

### CODE REVIEW

**Comment by jyao1** [comment]
@xiangfeima would you please take a look?

**Comment by xiangfeima** [comment]
Sure, I'm looking into it now.

**Comment by xiangfeima** [comment]
In the original ECP384 and ECP521 certificates for testing, the subject name all wrongly set to "ECP256", such as "DMTF libspdm ECP256 CA" or " DMTF libspdm ECP256 intermediate cert", "DMTF libspdm ECP256 requseter cert".
In https://github.com/DMTF/libspdm/commit/c4bd8d17fc6dd0956cfe7297a8eb4e18e6f427bf those certificatse were updated to proper subject name according to its algorithm and also new keys were generated.
However `bundle_requester.certchain.der` for each algorithm was updated but `bundle_requester.certchain1.der` was left without updating.
I'm very sorry for the missing.
Anyway I think we just need to update `bundle_requester.certchain1.der` instead of a whole restore.

Reference: https://github.com/DMTF/libspdm/pull/1956#discussion_r1172115513

**Comment by Wenxing-hou** [comment]
> In the original ECP384 and ECP521 certificates for testing, the subject name all wrongly set to "ECP256", such as "DMTF libspdm ECP256 CA", " DMTF libspdm ECP256 intermediate cert", "DMTF libspdm ECP256 requseter cert" (ECP384 or ECP521 it should be).
> In [c4bd8d1](https://github.com/DMTF/libspdm/commit/c4bd8d17fc6dd0956cfe7297a8eb4e18e6f427bf) those certificatse were updated to proper subject name according to its algorithm and also new keys were generated.
> However `bundle_requester.certchain.der` for each algorithm was updated but `bundle_requester.certchain1.der` was left without updating.
> I'm very sorry for the missing.
> Anyway I think we just need to update `bundle_requester.certchain1.der` instead of a whole restore.

Thanks. I will update the `bundle_requester.certchain1.der` for ecp384 and ecp521.

**Comment by xiangfeima** [comment]
@Wenxing-hou Thanks a lot. Would you help to take a look all the test certificates/keys for slot 1? I'm not sure if `bundle_requester.certchain1.der` is the only one need to be updated.

**Pull request merged**
