### PR TITLE
Update the overdue long_chains cert

### PR DESCRIPTION
**Pull request by Wenxing-hou**
Fix: #318 
Unite test error because of overdue long_chains cert.

Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
looks good

**Comment by jyao1** [comment]
Can we also add readme on how to generate this cert?

**Comment by Wenxing-hou** [comment]
Yes. I will update the readme.

**Comment by jyao1** [comment]
looks good

**Review by steven-bellock — APPROVED** [review]

**Pull request merged**
