### PR TITLE
Add conditional compile switches for CERT and CHAL capabilities.

### PR DESCRIPTION
**Pull request by rkongintel**
libspdm/issues/2.

Signed-off-by: Kong, Richard <richard.kong@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
I don't recommend to use SPDM_ENABLE_*_CAP in spdm.h.
The spdm.h just follows SPDM spec, and SPDM spec does not have such concept.

All rest seems good to me.

**Comment by rkongintel** [comment]
@jyao1 Are you saying I should leave the request/response structures in spdm.h always visibly defined to the compiler (not #if'd out)? I was doing that to ensure we don't miss any code that we should be disabling. Any idea how else I could make sure all code that should be disabled, actually is disabled?

**Comment by jyao1** [comment]
> @jyao1 Are you saying I should leave the request/response structures in spdm.h always visibly defined to the compiler (not #if'd out)? I was doing that to ensure we don't miss any code that we should be disabling. Any idea how else I could make sure all code that should be disabled, actually is disabled?

Right. That is my idea. The original purpose of spdm_lib_config.h is to configure the spdm_lib, but not the spec.

I am worried, because that enforces people to include spdm_lib_config.h to properly configure the specification. E.g. spdm-dump, or UEFI consumer.  That is extra complexity.

I can understand that your requirement seems to have a way to configure the specification. As such, no definition will be appeared. I think it is valid request. Capability is one example, I feel SPDM version is another example in the future.

If so, I am thinking to have a separate .h to perform that, such as spdm_spec_config.h. Worth discussing.

**Comment by jyao1** [comment]
Is there any size estimation after we use these flags?

**Comment by rkongintel** [comment]
I did not collect any measurements. Figured I would after we did our changes for all the capabilities.

**Pull request merged**
