### PR TITLE
Add fuzz testing for MEASUREMENT_EXTENSION_LOG.

### PR DESCRIPTION
**Pull request by Xiaohanjlll**
```
libspdm_req_get_measurement_extension_log.c
- Fuzz testing coverage : 77.9%
- 
- run time : 1 days, 00 hrs, 00 min, 00 sec
- 
- overall results :
-   cycles done :   351  
-   corpus count :  27   
-   saved crashes : 0 
-   saved hangs :   0 

libspdm_rsp_measurement_extension_log.c
- Fuzz testing coverage : 77.8 %
- 
- run time : 1 days, 00 hrs, 00 min, 00 sec
- 
- overall results :
-   cycles done :   2163  
-   corpus count :  34   
-   saved crashes : 0 
-   saved hangs :   0 
```

### CODE REVIEW

**Comment by Zhiqiang520** [comment]
It looks good to me.

**Comment by jyao1** [comment]
Please use the latest template for CMAKE file.

**Comment by Xiaohanjlll** [comment]
> Please use the latest template for CMAKE file.

Thanks, I have modified it to the latest template of the CMAKE file.

**Comment by steven-bellock** [comment]
@jyao1 feel free to merge as you see fit.

**Pull request merged**
