### PR TITLE
Armclang with MSYS2 on Windows

### PR DESCRIPTION
**Pull request by qizhangz**

### CODE REVIEW

**Comment by qizhangz** [comment]
os_stub/mbedtlslib/mbedtls:
diff --git a/library/CMakeLists.txt b/library/CMakeLists.txt
index fb0b5e134..444879aea 100644
--- a/library/CMakeLists.txt
+++ b/library/CMakeLists.txt
@@ -126,7 +126,7 @@ if(CMAKE_COMPILER_IS_CLANG)
 endif(CMAKE_COMPILER_IS_CLANG)

 if(WIN32)
-    set(libs ${libs} ws2_32)
+    #set(libs ${libs} ws2_32)
 endif(WIN32)

 if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
diff --git a/library/entropy_poll.c b/library/entropy_poll.c
index 2c1e0937b..c098e58aa 100644
--- a/library/entropy_poll.c
+++ b/library/entropy_poll.c
@@ -42,7 +42,7 @@
 #include "mbedtls/platform.h"
 #endif

-#if !defined(MBEDTLS_NO_PLATFORM_ENTROPY)
+#if 0//!defined(MBEDTLS_NO_PLATFORM_ENTROPY)

 #if !defined(unix) && !defined(__unix__) && !defined(__unix) && \
     !defined(__APPLE__) && !defined(_WIN32) && !defined(__QNXNTO__) && \

**Comment by qizhangz** [comment]
unit_test/cmockalib/cmocka:
diff --git a/src/cmocka.c b/src/cmocka.c
index 2dda20a..cae2d3f 100644
--- a/src/cmocka.c
+++ b/src/cmocka.c
@@ -2652,6 +2652,7 @@ static void cmprintf_tap(enum cm_printf_type type,
         print_message("ok %u - %s\n", (unsigned)test_number, test_name);
         break;
     case PRINTF_TEST_FAILURE:
+#if 0
         print_message("not ok %u - %s\n", (unsigned)test_number, test_name);
         if (error_message != NULL) {
             char *msg;
@@ -2680,6 +2681,7 @@ static void cmprintf_tap(enum cm_printf_type type,
             }
             libc_free(msg);
         }
+#endif
         break;
     case PRINTF_TEST_SKIPPED:
         print_message("ok %u # SKIP %s\n", (unsigned)test_number, test_name);

**Comment by qizhangz** [comment]
To pass armclang build and link with MSYS2, need to apply the above changes in mbedtls and cmocka temporarily.

**Comment by Wenxing-hou** [comment]
I have changed the CMakeLists.txt to make the windows armclang aarch64 build.

image

**Pull request closed without merging**
