### PR TITLE
Add appropriate assert for capabbility in spdm_set_data()

### PR DESCRIPTION
**Pull request by Wenxing-hou**
Fix: #205 

Signed-off-by: Wenxing Hou <wenxing.hou@intel.com>

### CODE REVIEW

**Comment by liyi77** [comment]
Hi Wenxin, have you test it with spdm_emu?
I think there will be problems when testing it with emu.

**Comment by Wenxing-hou** [comment]
Hi Liyi. I have tested it with spdm_emu. And the test pass. Thanks.

**Comment by liyi77** [comment]
Have you try to disable SPDM_ENABLE_CAPABILITY_MEAS_CAP and test it?
like: #define SPDM_ENABLE_CAPABILITY_MEAS_CAP 0
I found some error at this case, 
BUT it maybe not trigger by this patch.

**Comment by Wenxing-hou** [comment]
Yes, I have tested the disable SPDM_ENABLE_CAPABILITY_XXX_CAP case yesterday morning. Some error is found. But it is not this patch's reason. It is because that spdm-emu call wrong function when disable SPDM_ENABLE_CAPABILITY_XXX_CAP. I will generate a issue in spdm-emu. Thanks.

**Comment by jyao1** [comment]
looks good

**Review by steven-bellock — APPROVED** [review]

**Pull request merged**
