### PR TITLE
cache all peer certificates per slot.

### PR DESCRIPTION
**Pull request by qizhangz**
Fix: #836 

Signed-off-by: Qi Zhang <qi1.zhang@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
Do we have a unit test cover:
GetCert (Slot 0), GetCert (Slot 1), Challenge (Slot 0) ?

**Comment by jyao1** [comment]
Do we have a unit test cover:
GetCert (Slot 0), GetCert (Slot 1), Challenge (Slot 0) ?

**Comment by qizhangz** [comment]
> Do we have a unit test cover: GetCert (Slot 0), GetCert (Slot 1), Challenge (Slot 0) ?
I need the below PR to get GetCert (Slot 0), GetCert (Slot 1). Could you please review it?

https://github.com/DMTF/libspdm/pull/895

**Comment by jyao1** [comment]
#895 is merged. Please design the new test to increase coverage

**Comment by qizhangz** [comment]
> Do we have a unit test cover: GetCert (Slot 0), GetCert (Slot 1), Challenge (Slot 0) ?

We created unit test for such case.

**Review by jyao1 — CHANGES_REQUESTED** [review]
Please use get_cert(0), get_cert(1), challenge (0) in unit test without context change.

**Review by jyao1 — APPROVED** [review]

**Comment by jyao1** [comment]
merge it together with emu, so that we can start test.

feel free to leave more feedback, if you find something need improve later.

**Pull request merged**
