### PR TITLE
Split `libspdm_send_receive_data` into separate functions

### LINKED ISSUE #1831: Add 2 more APIs libspdm_send_data and libspdm_receive_data
Currently the function of libspdm_send_receive_data send and receive an SPDM or APP message in one call.
There is no functions to send and receive data separately. In some scenarios sending and receiving may be separated.
Can we add 2 more APIs (libspdm_send_data / libspdm_receive_data) to do above tasks?

### PR DESCRIPTION
**Pull request by steven-bellock**
Fix #1831.

Signed-off-by: Steven Bellock <sbellock@nvidia.com>

### CODE REVIEW

**Comment by steven-bellock** [comment]
@mxu9 for your review as well.

**Comment by jyao1** [comment]
Would you please squash the coding style fix?

**Comment by steven-bellock** [comment]
> Would you please squash the coding style fix?

It is done.

**Review by mxu9 — APPROVED** [review]
It's good to me.

**Pull request merged**
