### PR TITLE
Generate stack usage information with -fstack-usage.

### PR DESCRIPTION
**Pull request by qizhangz**
Fix: #275 

Generate an extra file that specifies the maximum amount of stack used, on a per-function basis.

Signed-off-by: Qi Zhang <qi1.zhang@intel.com>

### CODE REVIEW

**Comment by jyao1** [comment]
Please add one section in document (https://github.com/DMTF/libspdm/blob/main/doc/test.md) on
1) how to collect the data.
2) sample output.

Question: Is there any solution in Windows/MSVC?

**Comment by jyao1** [comment]
Do you need mention https://dlbeer.co.nz/oss/avstack.html ?

**Comment by jyao1** [comment]
looks good

**Review by steven-bellock — APPROVED** [review]

**Comment by qizhangz** [comment]
conflict resolved.

**Pull request merged**
